-- ============================================================================
-- 0009_bracket_functions.sql
-- Bracket persistence + advancement.
--   * create_bracket(competition, structure) — persist a generated bracket and
--     open the first playable matchups (resolving byes).
--   * advance_bracket(event, winner)          — service-role only; called by the
--     settlement engine when a matchup settles. Fills the next slot and opens
--     the next matchup once both competitors are known.
-- ============================================================================

-- Create the event + market + two options for a ready matchup slot.
create or replace function app.generate_matchup_event(p_slot_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot bracket_slots%rowtype;
  v_comp competitions%rowtype;
  v_round bracket_rounds%rowtype;
  v_event_id uuid;
  v_market_id uuid;
  v_name_a text; v_color_a text;
  v_name_b text; v_color_b text;
begin
  select * into v_slot from bracket_slots where id = p_slot_id;
  if v_slot.event_id is not null then return v_slot.event_id; end if;
  if v_slot.competitor_a_id is null or v_slot.competitor_b_id is null then return null; end if;

  select * into v_comp from competitions where id = v_slot.competition_id;
  select * into v_round from bracket_rounds where id = v_slot.round_id;
  select name, color into v_name_a, v_color_a from competitors where id = v_slot.competitor_a_id;
  select name, color into v_name_b, v_color_b from competitors where id = v_slot.competitor_b_id;

  insert into events (tenant_id, competition_id, creator_id, title, slug, status, result_source, metadata)
  values (v_comp.tenant_id, v_comp.id, v_comp.creator_id,
          v_round.name || ' · ' || v_name_a || ' vs ' || v_name_b,
          v_comp.slug || '-m' || v_slot.match_index, 'open', 'creator_manual',
          jsonb_build_object('bracket_match_index', v_slot.match_index))
  returning id into v_event_id;

  insert into markets (tenant_id, event_id, question, type, status)
  values (v_comp.tenant_id, v_event_id, 'Which competitor will win?', 'SINGLE_CHOICE_WINNER', 'open')
  returning id into v_market_id;

  insert into market_options (tenant_id, market_id, competitor_id, label, color, display_order, status)
  values
    (v_comp.tenant_id, v_market_id, v_slot.competitor_a_id, v_name_a, v_color_a, 0, 'active'),
    (v_comp.tenant_id, v_market_id, v_slot.competitor_b_id, v_name_b, v_color_b, 1, 'active');

  update bracket_slots set event_id = v_event_id, status = 'ready' where id = p_slot_id;
  return v_event_id;
end;
$$;

-- Resolve byes, push winners into child seats, and open newly-ready matchups.
-- Idempotent and self-terminating (each step is guarded to make forward progress).
create or replace function app.propagate_bracket(p_competition_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_changed boolean := true;
  v_slot bracket_slots%rowtype;
begin
  while v_changed loop
    v_changed := false;

    -- 1. A bye's winner is its present competitor.
    for v_slot in select * from bracket_slots
      where competition_id = p_competition_id and is_bye and winner_competitor_id is null
    loop
      update bracket_slots set winner_competitor_id = v_slot.bye_competitor_id, status = 'decided'
        where id = v_slot.id;
      v_changed := true;
    end loop;

    -- 2. Push each decided winner into its child seat.
    for v_slot in select * from bracket_slots
      where competition_id = p_competition_id and winner_competitor_id is not null
    loop
      update bracket_slots child set competitor_a_id = v_slot.winner_competitor_id
        where child.source_a_id = v_slot.id and child.competitor_a_id is null;
      if found then v_changed := true; end if;
      update bracket_slots child set competitor_b_id = v_slot.winner_competitor_id
        where child.source_b_id = v_slot.id and child.competitor_b_id is null;
      if found then v_changed := true; end if;
    end loop;

    -- 3. Open events for ready matchups.
    for v_slot in select * from bracket_slots
      where competition_id = p_competition_id and not is_bye and event_id is null
        and competitor_a_id is not null and competitor_b_id is not null
        and winner_competitor_id is null
    loop
      perform app.generate_matchup_event(v_slot.id);
      v_changed := true;
    end loop;
  end loop;
end;
$$;

-- Persist a bracket generated by src/lib/domain/bracket.ts. Owner/super-admin only.
create or replace function public.create_bracket(p_competition_id uuid, p_structure jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_comp competitions%rowtype;
  v_round jsonb;
  v_match jsonb;
  v_round_id uuid;
  v_round_map jsonb := '{}'::jsonb;
begin
  select * into v_comp from competitions where id = p_competition_id;
  if not found then raise exception 'COMPETITION_NOT_FOUND' using errcode = 'P0002'; end if;
  if not (app.is_super_admin() or app.owns_creator(v_comp.creator_id)) then
    raise exception 'NOT_AUTHORIZED' using errcode = '42501';
  end if;
  if v_comp.type <> 'BRACKET' then raise exception 'NOT_A_BRACKET' using errcode = '22000'; end if;
  if exists (select 1 from bracket_rounds where competition_id = p_competition_id) then
    raise exception 'BRACKET_ALREADY_EXISTS' using errcode = '23505';
  end if;

  for v_round in select * from jsonb_array_elements(p_structure->'rounds') loop
    insert into bracket_rounds (tenant_id, competition_id, round_number, name, size)
    values (v_comp.tenant_id, p_competition_id, (v_round->>'round_number')::int,
            v_round->>'name', (v_round->>'size')::int)
    returning id into v_round_id;
    v_round_map := v_round_map || jsonb_build_object(v_round->>'round_number', v_round_id);
  end loop;

  -- Slots (competitors + byes; source links wired in the next pass).
  for v_match in select * from jsonb_array_elements(p_structure->'matches') loop
    insert into bracket_slots (tenant_id, competition_id, round_id, match_index, position,
      competitor_a_id, competitor_b_id, is_bye, bye_competitor_id)
    values (v_comp.tenant_id, p_competition_id,
      (v_round_map->>(v_match->>'round_number'))::uuid,
      (v_match->>'match_index')::int, (v_match->>'position')::int,
      nullif(v_match->>'competitor_a_id', '')::uuid, nullif(v_match->>'competitor_b_id', '')::uuid,
      coalesce((v_match->>'is_bye')::boolean, false), nullif(v_match->>'bye_competitor_id', '')::uuid);
  end loop;

  for v_match in select * from jsonb_array_elements(p_structure->'matches') loop
    if v_match ? 'source_a_index' and v_match->>'source_a_index' is not null then
      update bracket_slots child set source_a_id = src.id
        from bracket_slots src
        where child.competition_id = p_competition_id and child.match_index = (v_match->>'match_index')::int
          and src.competition_id = p_competition_id and src.match_index = (v_match->>'source_a_index')::int;
    end if;
    if v_match ? 'source_b_index' and v_match->>'source_b_index' is not null then
      update bracket_slots child set source_b_id = src.id
        from bracket_slots src
        where child.competition_id = p_competition_id and child.match_index = (v_match->>'match_index')::int
          and src.competition_id = p_competition_id and src.match_index = (v_match->>'source_b_index')::int;
    end if;
  end loop;

  perform app.propagate_bracket(p_competition_id);
end;
$$;

-- Advance a bracket after a matchup settles. Service-role only (settlement engine).
create or replace function public.advance_bracket(p_event_id uuid, p_winner_competitor_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_slot bracket_slots%rowtype;
begin
  select * into v_slot from bracket_slots where event_id = p_event_id;
  if not found then return; end if;  -- not a bracket matchup; nothing to do
  if p_winner_competitor_id is distinct from v_slot.competitor_a_id
     and p_winner_competitor_id is distinct from v_slot.competitor_b_id then
    raise exception 'WINNER_NOT_IN_MATCH' using errcode = '22000';
  end if;
  update bracket_slots set winner_competitor_id = p_winner_competitor_id, status = 'decided'
    where id = v_slot.id;
  perform app.propagate_bracket(v_slot.competition_id);
end;
$$;

-- Grants: create_bracket for owners (checked inside); advance_bracket service-only.
revoke all on function public.create_bracket(uuid, jsonb) from public;
grant execute on function public.create_bracket(uuid, jsonb) to authenticated, service_role;
revoke all on function public.advance_bracket(uuid, uuid) from public;
grant execute on function public.advance_bracket(uuid, uuid) to service_role;
